name: Flutter CI/CD para Teste e Deploy

# 1. GATILHO (TRIGGER)
on:
    # Executa sempre que houver um push para o branch 'main'.
    push:
        branches: [ main ]
    # Permite a execução manual a partir da UI do GitHub.
    workflow_dispatch:

# 2. VARIÁVEIS DE AMBIENTE
env:
    GCP_PROJECT_ID: 'test-integration-app-4e52e'
    FIREBASE_APP_ID: '1:424599350937:android:5c7fd412fffd453bcb5208'
    FIREBASE_TESTER_GROUP: 'qa-team'

# 3. TAREFAS (JOBS)
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do Repositório
              uses: actions/checkout@v4

            - name: Configurar Java JDK v17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Configurar Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.35.2'
                  channel: 'stable'

            # PASSO DE DEBUG: Verifica se o segredo está a ser carregado.
            - name: Verificar se o Segredo GCP_SA_KEY está presente
              run: |
                  if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
                    echo "ERRO: O segredo GCP_SA_KEY não foi encontrado ou está vazio."
                    exit 1
                  else
                    echo "SUCESSO: O segredo GCP_SA_KEY foi carregado."
                  fi

            - name: Autenticar no Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'

            - name: Validar Autenticação
              run: gcloud auth list

            - name: Configurar gcloud CLI
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ env.GCP_PROJECT_ID }}

            - name: Instalar Firebase CLI
              run: sudo npm install -g firebase-tools

            - name: Construir APKs e Executar Testes no Firebase Test Lab
              run: |
                  flutter pub get
                  flutter build apk --debug
                  flutter build apk --debug --target integration_test/app_test.dart
                  
                  gcloud firebase test android run \
                    --type instrumentation \
                    --app build/app/outputs/flutter-apk/app-debug.apk \
                    --test build/app/outputs/flutter-apk/app-debug-androidTest.apk \
                    --device model=redfin,version=30,locale=pt_BR,orientation=portrait \
                    --timeout 15m

            - name: Distribuir para QA no Firebase App Distribution
              run: |
                  firebase appdistribution:distribute build/app/outputs/apk/debug/app-debug.apk \
                    --app ${{ env.FIREBASE_APP_ID }} \
                    --release-notes "Build ${{ github.run_number }} - Aprovado nos testes." \
                    --groups "${{ env.FIREBASE_TESTER_GROUP }}"

